const ALLOWED_TABLES = new Set([
  // Core commercial data.
  'abonos_cxc',
  'abonos_cxp',
  'activos_fijos',
  'api_eventos_pendientes',
  'attachments',
  'bodegas',
  'caja_sesiones',
  'cierres_caja',
  'clientes',
  'comisiones_liquidadas',
  'comisiones_vendedor',
  'commission_rules',
  'commissions',
  'comprobantes_contables',
  'cotizacion_detalle',
  'cotizaciones',
  'cuentas_contables',
  'cuentas_por_cobrar',
  'devoluciones_compras',
  'devoluciones_compras_detalle',
  'devoluciones_ventas',
  'devoluciones_ventas_detalle',
  'documentos_compra_flujo',
  'documentos_compra_flujo_lineas',
  'documentos_venta_flujo',
  'documentos_venta_flujo_lineas',
  'empleados',
  'enterprise_audit_log',
  'enterprise_fixed_assets',
  'enterprise_tax_calculations',
  'enterprise_tax_rules',
  'facturas_electronicas',
  'fixed_asset_events',
  'inventory_lots',
  'inventory_reservations',
  'kardex_inventario',
  'lotes',
  'movimientos_caja',
  'movimientos_inventario',
  'nomina_liquidaciones',
  'order_lines',
  'payment_transactions',
  'pedidos',
  'pedido_detalle',
  'productos',
  'proveedores',
  'purchase_document_audit',
  'purchase_document_lines',
  'purchase_documents',
  'quote_lines',
  'reglas_impuestos_empresa',
  'reglas_retenciones_empresa',
  'sales_document_audit',
  'sales_document_lines',
  'sales_documents',
  'sales_orders',
  'sales_quotes',
  'series',
  'stock_bodega',
  'supplier_balances',
  'transferencias',
  'traslados_bodega',
  'treasury_bank_accounts',
  'treasury_bank_movements',
  'treasury_transfers',
  'warranty_claims',
  'warranties',

  // CRM, HRM, MRP and cross-module UX features added after the first sync.
  'crm_contacts',
  'crm_leads',
  'crm_opportunities',
  'crm_interactions',
  'crm_campaigns',
  'crm_territories',
  'crm_opportunity_items',
  'crm_oportunidades',
  'crm_actividades',
  'crm_timeline',
  'crm_notifications',
  'hrm_attendance_records',
  'hrm_job_titles',
  'hrm_leaves',
  'hrm_leave_entitlements',
  'hrm_leave_requests',
  'hrm_leave_types',
  'impact_scenarios',
  'mrp_bom_items',
  'mrp_boms',
  'mrp_operations',
  'mrp_routings',
  'mrp_work_order_items',
  'mrp_work_orders',
  'mrp_workstation_shifts',
  'mrp_workstations',

  // Public-sector multi-tenant base and audit trail.
  'auditoria_registros',
  'configuracion_entidad',
  'configuracion_visibilidad',
  'configuraciones_generales',
  'consolidacion_nicsp40',
  'entidades_territoriales',
  'funcionarios_entidad',
  'modulos_por_tipo_entidad',
  'plan_cuentas_cgc',
  'terceros_sector_publico',
  'usuarios_sector_publico',

  // Public-sector budgeting, planning and SIIF/CHIP/FUT reporting.
  'apropiaciones',
  'autorizaciones_vigencias_futuras',
  'cdp_meta_trazabilidad',
  'cdps',
  'compromisos_vigencias_futuras',
  'embargos_judiciales',
  'estampillas_parafiscales',
  'flujos_viabilizacion',
  'incidentes_recibido_sin_obligacion',
  'obligaciones',
  'obligaciones_vigencias_futuras',
  'pac',
  'pagos',
  'pdt',
  'proyecto_rubros_metas',
  'proyectos_mga',
  'recepciones_satisfaccion',
  'reportes_chip',
  'reportes_fut_territorial',
  'reportes_sia_observa',
  'reportes_siif_nacion',
  'rp_meta_trazabilidad',
  'rps',
  'vigencias_futuras_distribucion',

  // Public-sector accounting, NICSP 40 and assets.
  'actas_responsabilidad',
  'activos_estado',
  'asientos_contables_sp',
  'cierres_vigencia',
  'conciliaciones_reciprocas',
  'conciliaciones_reciprocas_partidas',
  'configuracion_depreciacion',
  'configuracion_depreciacion_unidades',
  'consolidaciones_nicsp40',
  'detalles_asientos',
  'fondo_unidad_tesoreria',
  'provisiones',
  'registros_produccion',
  'revalorizaciones',
  'saldos_cuentas',

  // Public-sector procurement, payroll, health, taxes, SGP/SGR and transparency.
  'acuerdos_pago',
  'avisos_tablero',
  'bienios_sgr',
  'catalogo_cie10',
  'catalogo_cups',
  'censo_ica',
  'contratos',
  'contratos_eps_adres',
  'declaraciones_ica',
  'empleados_sp',
  'facturas_salud',
  'glosas',
  'horas_extra',
  'liquidaciones_nomina',
  'liquidaciones_prediales',
  'pagos_ica',
  'polizas',
  'predios',
  'procesos_cobro_coactivo',
  'procesos_contratacion',
  'procesos_disciplinarios',
  'proyectos_ocad',
  'recargos',
  'regalias',
  'reportes_spgr',
  'reportes_sicodis',
  'reportes_transparencia',
  'reteica',
  'retroactivos',
  'rips',
  'rips_fev_documentos',
  'sgp',
  'sgp_destinaciones_rubro',
  'tarifas_prediales'
]);

function normalizeTableName(tableName) {
  return typeof tableName === 'string' ? tableName.trim() : '';
}

function isAllowedTable(tableName) {
  return ALLOWED_TABLES.has(normalizeTableName(tableName));
}

module.exports = {
  ALLOWED_TABLES,
  isAllowedTable,
  normalizeTableName
};
