services:
  - type: web
    name: merka-control-center-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    databases:
      - name: merkaerp-postgres
        databaseName: merkaerp
        user: merkaerp_user
